# Generated by Django 2.2 on 2019-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.CharField(default='hi this my first post', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(default='post itext', max_length=20),
            preserve_default=False,
        ),
    ]
