# Generated by Django 2.2 on 2019-07-22 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190722_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='post_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_img'),
        ),
    ]
