# Generated by Django 2.2 on 2019-07-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190722_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_title',
            field=models.CharField(default='mypost', max_length=50),
        ),
    ]
