# Generated by Django 2.2 on 2019-07-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_title',
            field=models.CharField(max_length=50),
        ),
    ]
