# Generated by Django 2.2 on 2019-07-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_comments_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
