# Generated by Django 2.2 on 2019-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190727_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_likes',
            old_name='like',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
