# Generated by Django 2.2 on 2019-07-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190727_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_likes',
            old_name='likes',
            new_name='like',
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
